'use strict';
import './assets/styles/button.css';
import './assets/styles/header.css';
import './assets/styles/title.css';
import './assets/styles/text.css';
import './assets/styles/hero.css';
import './assets/styles/user-case.css';
import './assets/styles/slider.css';
import './assets/styles/message.css';
import './assets/styles/code.css';
import './assets/styles/feature.css';
import './assets/styles/link.css';
import './assets/styles/quick-start.css';
import './assets/styles/api.css';
import './assets/styles/community.css';
import './style.css';

import './assets/images/logo.svg';
import './assets/images/sun.svg';
import './assets/images/moon.svg';
import './assets/images/ava_duck.svg';
import './assets/images/ava_alian.svg';
import './assets/images/ava_star.svg';
import './assets/images/ava_alpaca.svg';
import './assets/images/ava_dog.svg';
import './assets/images/phone.png';
import './assets/images/phone_small.png';
import './assets/images/bnb.svg';
import './assets/images/btc.svg';
import './assets/images/eth.svg';
import './assets/images/ltc.svg';
import './assets/images/ton.svg';
import './assets/images/trx.svg';
import './assets/images/usdc.svg';
import './assets/images/usdt.svg';
import './assets/images/tg_background.jpg';
import './assets/images/telegram.svg';
import './assets/images/api.png';
import './assets/images/js.svg';
import './assets/images/net.svg';
import './assets/images/php.svg';
import './assets/images/python.svg';
import './assets/images/go.svg';


const $root = document.getElementById('root');
console.log($root);
$root.append('Все Будет сдорово, все будет красиво');
